Image upload
infigram/infigram-back pull request #4
Opened 2020-08-02 00:17 UTC by ZeroDiverse

2020-08-02 10:15 UTC, BhavyaCodes requested changes
Images get saved to cloudinary despite not passing validation, so post doesn't get saved to mongodb but image does. Needs to be fixed

2020-08-05 13:30 UTC, BhavyaCodes approved these changes

2020-08-06 07:33 UTC, Juggernaut9 commented
Validation of form fields had been fixed

2020-08-06 07:40 UTC, RickyDoesCode approved these changes
LGTM!

2020-08-06 07:40 UTC, merged